std_msgs/Float32MultiArray   cartesian_pose
---
std_msgs/Float32MultiArray   articular_pose
std_msgs/Float32  	     torso_pose			     
geometry_msgs/Pose2D 	     base_correction

#The intended use of this service is as follows:
#If cartesian_pose has six elements, then, the corresponding seven articular positions are calculated
#If cartesian_pose has six values (xyzrpy)

#Result is an array of five floats representing the angular position for each motor in the arm 
# [  arm_flex_joint
#   arm_roll_joint
#   wrist_flex_joint
#   wrist_roll_joint]

# omni_base_correction are variables for omni_base robot to correct gripper pose.
# torso pose is a variable for torso control