// Generated by gencpp from file sp_rec/ActivateDictionariesRequest.msg
// DO NOT EDIT!


#ifndef SP_REC_MESSAGE_ACTIVATEDICTIONARIESREQUEST_H
#define SP_REC_MESSAGE_ACTIVATEDICTIONARIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sp_rec
{
template <class ContainerAllocator>
struct ActivateDictionariesRequest_
{
  typedef ActivateDictionariesRequest_<ContainerAllocator> Type;

  ActivateDictionariesRequest_()
    : names()
    , active(false)  {
    }
  ActivateDictionariesRequest_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , active(false)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef uint8_t _active_type;
  _active_type active;




  typedef boost::shared_ptr< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActivateDictionariesRequest_

typedef ::sp_rec::ActivateDictionariesRequest_<std::allocator<void> > ActivateDictionariesRequest;

typedef boost::shared_ptr< ::sp_rec::ActivateDictionariesRequest > ActivateDictionariesRequestPtr;
typedef boost::shared_ptr< ::sp_rec::ActivateDictionariesRequest const> ActivateDictionariesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sp_rec

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46df45e75d9f229d774f216ebda62258";
  }

  static const char* value(const ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46df45e75d9f229dULL;
  static const uint64_t static_value2 = 0x774f216ebda62258ULL;
};

template<class ContainerAllocator>
struct DataType< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sp_rec/ActivateDictionariesRequest";
  }

  static const char* value(const ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string[] names\n\
\n\
\n\
bool active\n\
\n\
";
  }

  static const char* value(const ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivateDictionariesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sp_rec::ActivateDictionariesRequest_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SP_REC_MESSAGE_ACTIVATEDICTIONARIESREQUEST_H
