// Generated by gencpp from file mvn_pln/mp_getclose_xyRequest.msg
// DO NOT EDIT!


#ifndef MVN_PLN_MESSAGE_MP_GETCLOSE_XYREQUEST_H
#define MVN_PLN_MESSAGE_MP_GETCLOSE_XYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace mvn_pln
{
template <class ContainerAllocator>
struct mp_getclose_xyRequest_
{
  typedef mp_getclose_xyRequest_<ContainerAllocator> Type;

  mp_getclose_xyRequest_()
    : goalX()
    , goalY()  {
    }
  mp_getclose_xyRequest_(const ContainerAllocator& _alloc)
    : goalX(_alloc)
    , goalY(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _goalX_type;
  _goalX_type goalX;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _goalY_type;
  _goalY_type goalY;




  typedef boost::shared_ptr< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mp_getclose_xyRequest_

typedef ::mvn_pln::mp_getclose_xyRequest_<std::allocator<void> > mp_getclose_xyRequest;

typedef boost::shared_ptr< ::mvn_pln::mp_getclose_xyRequest > mp_getclose_xyRequestPtr;
typedef boost::shared_ptr< ::mvn_pln::mp_getclose_xyRequest const> mp_getclose_xyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mvn_pln

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9061aee48320f865b73af2589fed8f03";
  }

  static const char* value(const ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9061aee48320f865ULL;
  static const uint64_t static_value2 = 0xb73af2589fed8f03ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvn_pln/mp_getclose_xyRequest";
  }

  static const char* value(const ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 goalX\n\
std_msgs/Float32 goalY\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goalX);
      stream.next(m.goalY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mp_getclose_xyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvn_pln::mp_getclose_xyRequest_<ContainerAllocator>& v)
  {
    s << indent << "goalX: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.goalX);
    s << indent << "goalY: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.goalY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVN_PLN_MESSAGE_MP_GETCLOSE_XYREQUEST_H
