// Generated by gencpp from file mvn_pln/mp_move_dist_angleRequest.msg
// DO NOT EDIT!


#ifndef MVN_PLN_MESSAGE_MP_MOVE_DIST_ANGLEREQUEST_H
#define MVN_PLN_MESSAGE_MP_MOVE_DIST_ANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace mvn_pln
{
template <class ContainerAllocator>
struct mp_move_dist_angleRequest_
{
  typedef mp_move_dist_angleRequest_<ContainerAllocator> Type;

  mp_move_dist_angleRequest_()
    : bearing()
    , distance()  {
    }
  mp_move_dist_angleRequest_(const ContainerAllocator& _alloc)
    : bearing(_alloc)
    , distance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _bearing_type;
  _bearing_type bearing;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mp_move_dist_angleRequest_

typedef ::mvn_pln::mp_move_dist_angleRequest_<std::allocator<void> > mp_move_dist_angleRequest;

typedef boost::shared_ptr< ::mvn_pln::mp_move_dist_angleRequest > mp_move_dist_angleRequestPtr;
typedef boost::shared_ptr< ::mvn_pln::mp_move_dist_angleRequest const> mp_move_dist_angleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mvn_pln

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebb675b5ffe2861f054edd7cce6d60cd";
  }

  static const char* value(const ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebb675b5ffe2861fULL;
  static const uint64_t static_value2 = 0x054edd7cce6d60cdULL;
};

template<class ContainerAllocator>
struct DataType< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvn_pln/mp_move_dist_angleRequest";
  }

  static const char* value(const ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 bearing\n\
std_msgs/Float32 distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bearing);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mp_move_dist_angleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvn_pln::mp_move_dist_angleRequest_<ContainerAllocator>& v)
  {
    s << indent << "bearing: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.bearing);
    s << indent << "distance: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVN_PLN_MESSAGE_MP_MOVE_DIST_ANGLEREQUEST_H
