// Generated by gencpp from file mvn_pln/mp_obstacle.msg
// DO NOT EDIT!


#ifndef MVN_PLN_MESSAGE_MP_OBSTACLE_H
#define MVN_PLN_MESSAGE_MP_OBSTACLE_H

#include <ros/service_traits.h>


#include <mvn_pln/mp_obstacleRequest.h>
#include <mvn_pln/mp_obstacleResponse.h>


namespace mvn_pln
{

struct mp_obstacle
{

typedef mp_obstacleRequest Request;
typedef mp_obstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mp_obstacle
} // namespace mvn_pln


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvn_pln::mp_obstacle > {
  static const char* value()
  {
    return "938f9cc76650ee8bc7d6dc8275ba504b";
  }

  static const char* value(const ::mvn_pln::mp_obstacle&) { return value(); }
};

template<>
struct DataType< ::mvn_pln::mp_obstacle > {
  static const char* value()
  {
    return "mvn_pln/mp_obstacle";
  }

  static const char* value(const ::mvn_pln::mp_obstacle&) { return value(); }
};


// service_traits::MD5Sum< ::mvn_pln::mp_obstacleRequest> should match 
// service_traits::MD5Sum< ::mvn_pln::mp_obstacle > 
template<>
struct MD5Sum< ::mvn_pln::mp_obstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvn_pln::mp_obstacle >::value();
  }
  static const char* value(const ::mvn_pln::mp_obstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvn_pln::mp_obstacleRequest> should match 
// service_traits::DataType< ::mvn_pln::mp_obstacle > 
template<>
struct DataType< ::mvn_pln::mp_obstacleRequest>
{
  static const char* value()
  {
    return DataType< ::mvn_pln::mp_obstacle >::value();
  }
  static const char* value(const ::mvn_pln::mp_obstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvn_pln::mp_obstacleResponse> should match 
// service_traits::MD5Sum< ::mvn_pln::mp_obstacle > 
template<>
struct MD5Sum< ::mvn_pln::mp_obstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvn_pln::mp_obstacle >::value();
  }
  static const char* value(const ::mvn_pln::mp_obstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvn_pln::mp_obstacleResponse> should match 
// service_traits::DataType< ::mvn_pln::mp_obstacle > 
template<>
struct DataType< ::mvn_pln::mp_obstacleResponse>
{
  static const char* value()
  {
    return DataType< ::mvn_pln::mp_obstacle >::value();
  }
  static const char* value(const ::mvn_pln::mp_obstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVN_PLN_MESSAGE_MP_OBSTACLE_H
