// Generated by gencpp from file knowledge_msgs/GetPredefinedQuestions.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_GETPREDEFINEDQUESTIONS_H
#define KNOWLEDGE_MSGS_MESSAGE_GETPREDEFINEDQUESTIONS_H

#include <ros/service_traits.h>


#include <knowledge_msgs/GetPredefinedQuestionsRequest.h>
#include <knowledge_msgs/GetPredefinedQuestionsResponse.h>


namespace knowledge_msgs
{

struct GetPredefinedQuestions
{

typedef GetPredefinedQuestionsRequest Request;
typedef GetPredefinedQuestionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPredefinedQuestions
} // namespace knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::knowledge_msgs::GetPredefinedQuestions > {
  static const char* value()
  {
    return "68d94395b4ec7b52f8954f4e6ebf72fa";
  }

  static const char* value(const ::knowledge_msgs::GetPredefinedQuestions&) { return value(); }
};

template<>
struct DataType< ::knowledge_msgs::GetPredefinedQuestions > {
  static const char* value()
  {
    return "knowledge_msgs/GetPredefinedQuestions";
  }

  static const char* value(const ::knowledge_msgs::GetPredefinedQuestions&) { return value(); }
};


// service_traits::MD5Sum< ::knowledge_msgs::GetPredefinedQuestionsRequest> should match 
// service_traits::MD5Sum< ::knowledge_msgs::GetPredefinedQuestions > 
template<>
struct MD5Sum< ::knowledge_msgs::GetPredefinedQuestionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::knowledge_msgs::GetPredefinedQuestions >::value();
  }
  static const char* value(const ::knowledge_msgs::GetPredefinedQuestionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowledge_msgs::GetPredefinedQuestionsRequest> should match 
// service_traits::DataType< ::knowledge_msgs::GetPredefinedQuestions > 
template<>
struct DataType< ::knowledge_msgs::GetPredefinedQuestionsRequest>
{
  static const char* value()
  {
    return DataType< ::knowledge_msgs::GetPredefinedQuestions >::value();
  }
  static const char* value(const ::knowledge_msgs::GetPredefinedQuestionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::knowledge_msgs::GetPredefinedQuestionsResponse> should match 
// service_traits::MD5Sum< ::knowledge_msgs::GetPredefinedQuestions > 
template<>
struct MD5Sum< ::knowledge_msgs::GetPredefinedQuestionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::knowledge_msgs::GetPredefinedQuestions >::value();
  }
  static const char* value(const ::knowledge_msgs::GetPredefinedQuestionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowledge_msgs::GetPredefinedQuestionsResponse> should match 
// service_traits::DataType< ::knowledge_msgs::GetPredefinedQuestions > 
template<>
struct DataType< ::knowledge_msgs::GetPredefinedQuestionsResponse>
{
  static const char* value()
  {
    return DataType< ::knowledge_msgs::GetPredefinedQuestions >::value();
  }
  static const char* value(const ::knowledge_msgs::GetPredefinedQuestionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_GETPREDEFINEDQUESTIONS_H
