// Generated by gencpp from file knowledge_msgs/InitKDB.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_INITKDB_H
#define KNOWLEDGE_MSGS_MESSAGE_INITKDB_H

#include <ros/service_traits.h>


#include <knowledge_msgs/InitKDBRequest.h>
#include <knowledge_msgs/InitKDBResponse.h>


namespace knowledge_msgs
{

struct InitKDB
{

typedef InitKDBRequest Request;
typedef InitKDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitKDB
} // namespace knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::knowledge_msgs::InitKDB > {
  static const char* value()
  {
    return "7d40ee22877bfab4f2e1de8cb2e7b970";
  }

  static const char* value(const ::knowledge_msgs::InitKDB&) { return value(); }
};

template<>
struct DataType< ::knowledge_msgs::InitKDB > {
  static const char* value()
  {
    return "knowledge_msgs/InitKDB";
  }

  static const char* value(const ::knowledge_msgs::InitKDB&) { return value(); }
};


// service_traits::MD5Sum< ::knowledge_msgs::InitKDBRequest> should match 
// service_traits::MD5Sum< ::knowledge_msgs::InitKDB > 
template<>
struct MD5Sum< ::knowledge_msgs::InitKDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::knowledge_msgs::InitKDB >::value();
  }
  static const char* value(const ::knowledge_msgs::InitKDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowledge_msgs::InitKDBRequest> should match 
// service_traits::DataType< ::knowledge_msgs::InitKDB > 
template<>
struct DataType< ::knowledge_msgs::InitKDBRequest>
{
  static const char* value()
  {
    return DataType< ::knowledge_msgs::InitKDB >::value();
  }
  static const char* value(const ::knowledge_msgs::InitKDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::knowledge_msgs::InitKDBResponse> should match 
// service_traits::MD5Sum< ::knowledge_msgs::InitKDB > 
template<>
struct MD5Sum< ::knowledge_msgs::InitKDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::knowledge_msgs::InitKDB >::value();
  }
  static const char* value(const ::knowledge_msgs::InitKDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowledge_msgs::InitKDBResponse> should match 
// service_traits::DataType< ::knowledge_msgs::InitKDB > 
template<>
struct DataType< ::knowledge_msgs::InitKDBResponse>
{
  static const char* value()
  {
    return DataType< ::knowledge_msgs::InitKDB >::value();
  }
  static const char* value(const ::knowledge_msgs::InitKDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_INITKDB_H
