// Generated by gencpp from file knowledge_msgs/MapPredefinedQuestions.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_MAPPREDEFINEDQUESTIONS_H
#define KNOWLEDGE_MSGS_MESSAGE_MAPPREDEFINEDQUESTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct MapPredefinedQuestions_
{
  typedef MapPredefinedQuestions_<ContainerAllocator> Type;

  MapPredefinedQuestions_()
    : question()
    , answer()  {
    }
  MapPredefinedQuestions_(const ContainerAllocator& _alloc)
    : question(_alloc)
    , answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _question_type;
  _question_type question;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _answer_type;
  _answer_type answer;




  typedef boost::shared_ptr< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> const> ConstPtr;

}; // struct MapPredefinedQuestions_

typedef ::knowledge_msgs::MapPredefinedQuestions_<std::allocator<void> > MapPredefinedQuestions;

typedef boost::shared_ptr< ::knowledge_msgs::MapPredefinedQuestions > MapPredefinedQuestionsPtr;
typedef boost::shared_ptr< ::knowledge_msgs::MapPredefinedQuestions const> MapPredefinedQuestionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'knowledge_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a27d8629aeefd2b315942fe4a74ab143";
  }

  static const char* value(const ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa27d8629aeefd2b3ULL;
  static const uint64_t static_value2 = 0x15942fe4a74ab143ULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/MapPredefinedQuestions";
  }

  static const char* value(const ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string question\n\
string answer\n\
";
  }

  static const char* value(const ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.question);
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapPredefinedQuestions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::MapPredefinedQuestions_<ContainerAllocator>& v)
  {
    s << indent << "question: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.question);
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_MAPPREDEFINEDQUESTIONS_H
