// Generated by gencpp from file knowledge_msgs/PlanningCmdClips.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_PLANNINGCMDCLIPS_H
#define KNOWLEDGE_MSGS_MESSAGE_PLANNINGCMDCLIPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct PlanningCmdClips_
{
  typedef PlanningCmdClips_<ContainerAllocator> Type;

  PlanningCmdClips_()
    : name()
    , params()
    , id(0)
    , successful(0)  {
    }
  PlanningCmdClips_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , params(_alloc)
    , id(0)
    , successful(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _params_type;
  _params_type params;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _successful_type;
  _successful_type successful;




  typedef boost::shared_ptr< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningCmdClips_

typedef ::knowledge_msgs::PlanningCmdClips_<std::allocator<void> > PlanningCmdClips;

typedef boost::shared_ptr< ::knowledge_msgs::PlanningCmdClips > PlanningCmdClipsPtr;
typedef boost::shared_ptr< ::knowledge_msgs::PlanningCmdClips const> PlanningCmdClipsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'knowledge_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74450e6e60135cf7d80c9acedebf851b";
  }

  static const char* value(const ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74450e6e60135cf7ULL;
  static const uint64_t static_value2 = 0xd80c9acedebf851bULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/PlanningCmdClips";
  }

  static const char* value(const ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string params\n\
int32 id\n\
int32 successful\n\
";
  }

  static const char* value(const ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.params);
      stream.next(m.id);
      stream.next(m.successful);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningCmdClips_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::PlanningCmdClips_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "params: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.params);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "successful: ";
    Printer<int32_t>::stream(s, indent + "  ", v.successful);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_PLANNINGCMDCLIPS_H
