// Generated by gencpp from file knowledge_msgs/search_remember_faceResponse.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_SEARCH_REMEMBER_FACERESPONSE_H
#define KNOWLEDGE_MSGS_MESSAGE_SEARCH_REMEMBER_FACERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct search_remember_faceResponse_
{
  typedef search_remember_faceResponse_<ContainerAllocator> Type;

  search_remember_faceResponse_()
    : training_success(false)  {
    }
  search_remember_faceResponse_(const ContainerAllocator& _alloc)
    : training_success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _training_success_type;
  _training_success_type training_success;




  typedef boost::shared_ptr< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct search_remember_faceResponse_

typedef ::knowledge_msgs::search_remember_faceResponse_<std::allocator<void> > search_remember_faceResponse;

typedef boost::shared_ptr< ::knowledge_msgs::search_remember_faceResponse > search_remember_faceResponsePtr;
typedef boost::shared_ptr< ::knowledge_msgs::search_remember_faceResponse const> search_remember_faceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'knowledge_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aaffe7376155c795fd881e5816b01e10";
  }

  static const char* value(const ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaaffe7376155c795ULL;
  static const uint64_t static_value2 = 0xfd881e5816b01e10ULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/search_remember_faceResponse";
  }

  static const char* value(const ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool training_success\n\
\n\
";
  }

  static const char* value(const ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.training_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct search_remember_faceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::search_remember_faceResponse_<ContainerAllocator>& v)
  {
    s << indent << "training_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.training_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_SEARCH_REMEMBER_FACERESPONSE_H
