// Generated by gencpp from file knowledge_msgs/wait_for_commandRequest.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_WAIT_FOR_COMMANDREQUEST_H
#define KNOWLEDGE_MSGS_MESSAGE_WAIT_FOR_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct wait_for_commandRequest_
{
  typedef wait_for_commandRequest_<ContainerAllocator> Type;

  wait_for_commandRequest_()
    : timeout(0)  {
    }
  wait_for_commandRequest_(const ContainerAllocator& _alloc)
    : timeout(0)  {
  (void)_alloc;
    }



   typedef int32_t _timeout_type;
  _timeout_type timeout;




  typedef boost::shared_ptr< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct wait_for_commandRequest_

typedef ::knowledge_msgs::wait_for_commandRequest_<std::allocator<void> > wait_for_commandRequest;

typedef boost::shared_ptr< ::knowledge_msgs::wait_for_commandRequest > wait_for_commandRequestPtr;
typedef boost::shared_ptr< ::knowledge_msgs::wait_for_commandRequest const> wait_for_commandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'knowledge_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/planning/knowledge_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59c7c94880c7082d9353d4d0a3356213";
  }

  static const char* value(const ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59c7c94880c7082dULL;
  static const uint64_t static_value2 = 0x9353d4d0a3356213ULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/wait_for_commandRequest";
  }

  static const char* value(const ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 timeout\n\
";
  }

  static const char* value(const ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wait_for_commandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::wait_for_commandRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeout: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_WAIT_FOR_COMMANDREQUEST_H
