// Generated by gencpp from file knowledge_msgs/wait_for_command.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_WAIT_FOR_COMMAND_H
#define KNOWLEDGE_MSGS_MESSAGE_WAIT_FOR_COMMAND_H

#include <ros/service_traits.h>


#include <knowledge_msgs/wait_for_commandRequest.h>
#include <knowledge_msgs/wait_for_commandResponse.h>


namespace knowledge_msgs
{

struct wait_for_command
{

typedef wait_for_commandRequest Request;
typedef wait_for_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wait_for_command
} // namespace knowledge_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::knowledge_msgs::wait_for_command > {
  static const char* value()
  {
    return "f286b9f490839fee63da1e5ff1e054a7";
  }

  static const char* value(const ::knowledge_msgs::wait_for_command&) { return value(); }
};

template<>
struct DataType< ::knowledge_msgs::wait_for_command > {
  static const char* value()
  {
    return "knowledge_msgs/wait_for_command";
  }

  static const char* value(const ::knowledge_msgs::wait_for_command&) { return value(); }
};


// service_traits::MD5Sum< ::knowledge_msgs::wait_for_commandRequest> should match 
// service_traits::MD5Sum< ::knowledge_msgs::wait_for_command > 
template<>
struct MD5Sum< ::knowledge_msgs::wait_for_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::knowledge_msgs::wait_for_command >::value();
  }
  static const char* value(const ::knowledge_msgs::wait_for_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowledge_msgs::wait_for_commandRequest> should match 
// service_traits::DataType< ::knowledge_msgs::wait_for_command > 
template<>
struct DataType< ::knowledge_msgs::wait_for_commandRequest>
{
  static const char* value()
  {
    return DataType< ::knowledge_msgs::wait_for_command >::value();
  }
  static const char* value(const ::knowledge_msgs::wait_for_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::knowledge_msgs::wait_for_commandResponse> should match 
// service_traits::MD5Sum< ::knowledge_msgs::wait_for_command > 
template<>
struct MD5Sum< ::knowledge_msgs::wait_for_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::knowledge_msgs::wait_for_command >::value();
  }
  static const char* value(const ::knowledge_msgs::wait_for_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowledge_msgs::wait_for_commandResponse> should match 
// service_traits::DataType< ::knowledge_msgs::wait_for_command > 
template<>
struct DataType< ::knowledge_msgs::wait_for_commandResponse>
{
  static const char* value()
  {
    return DataType< ::knowledge_msgs::wait_for_command >::value();
  }
  static const char* value(const ::knowledge_msgs::wait_for_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_WAIT_FOR_COMMAND_H
