(cl:in-package vision_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          CATEGORY-VAL
          CATEGORY
          CONFIDENCE-VAL
          CONFIDENCE
          IMAGE-VAL
          IMAGE
          POINT_CLOUD-VAL
          POINT_CLOUD
          SIZE-VAL
          SIZE
          POSE-VAL
          POSE
          BOUNDING_BOX-VAL
          BOUNDING_BOX
          BOUNDING_POLYGON-VAL
          BOUNDING_POLYGON
          X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          GRASPABLE-VAL
          GRASPABLE
))