// Generated by gencpp from file navig_msgs/PlanPath.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_PLANPATH_H
#define NAVIG_MSGS_MESSAGE_PLANPATH_H

#include <ros/service_traits.h>


#include <navig_msgs/PlanPathRequest.h>
#include <navig_msgs/PlanPathResponse.h>


namespace navig_msgs
{

struct PlanPath
{

typedef PlanPathRequest Request;
typedef PlanPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanPath
} // namespace navig_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navig_msgs::PlanPath > {
  static const char* value()
  {
    return "d4c7fd7dba298b47cf73caf450fd8a9f";
  }

  static const char* value(const ::navig_msgs::PlanPath&) { return value(); }
};

template<>
struct DataType< ::navig_msgs::PlanPath > {
  static const char* value()
  {
    return "navig_msgs/PlanPath";
  }

  static const char* value(const ::navig_msgs::PlanPath&) { return value(); }
};


// service_traits::MD5Sum< ::navig_msgs::PlanPathRequest> should match 
// service_traits::MD5Sum< ::navig_msgs::PlanPath > 
template<>
struct MD5Sum< ::navig_msgs::PlanPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navig_msgs::PlanPath >::value();
  }
  static const char* value(const ::navig_msgs::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navig_msgs::PlanPathRequest> should match 
// service_traits::DataType< ::navig_msgs::PlanPath > 
template<>
struct DataType< ::navig_msgs::PlanPathRequest>
{
  static const char* value()
  {
    return DataType< ::navig_msgs::PlanPath >::value();
  }
  static const char* value(const ::navig_msgs::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navig_msgs::PlanPathResponse> should match 
// service_traits::MD5Sum< ::navig_msgs::PlanPath > 
template<>
struct MD5Sum< ::navig_msgs::PlanPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navig_msgs::PlanPath >::value();
  }
  static const char* value(const ::navig_msgs::PlanPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navig_msgs::PlanPathResponse> should match 
// service_traits::DataType< ::navig_msgs::PlanPath > 
template<>
struct DataType< ::navig_msgs::PlanPathResponse>
{
  static const char* value()
  {
    return DataType< ::navig_msgs::PlanPath >::value();
  }
  static const char* value(const ::navig_msgs::PlanPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_PLANPATH_H
