// Generated by gencpp from file navig_msgs/PlanPathRequest.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_PLANPATHREQUEST_H
#define NAVIG_MSGS_MESSAGE_PLANPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace navig_msgs
{
template <class ContainerAllocator>
struct PlanPathRequest_
{
  typedef PlanPathRequest_<ContainerAllocator> Type;

  PlanPathRequest_()
    : start_pose()
    , goal_pose()
    , start_location_id()
    , goal_location_id()  {
    }
  PlanPathRequest_(const ContainerAllocator& _alloc)
    : start_pose(_alloc)
    , goal_pose(_alloc)
    , start_location_id(_alloc)
    , goal_location_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _start_pose_type;
  _start_pose_type start_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _start_location_id_type;
  _start_location_id_type start_location_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_location_id_type;
  _goal_location_id_type goal_location_id;




  typedef boost::shared_ptr< ::navig_msgs::PlanPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navig_msgs::PlanPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanPathRequest_

typedef ::navig_msgs::PlanPathRequest_<std::allocator<void> > PlanPathRequest;

typedef boost::shared_ptr< ::navig_msgs::PlanPathRequest > PlanPathRequestPtr;
typedef boost::shared_ptr< ::navig_msgs::PlanPathRequest const> PlanPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navig_msgs::PlanPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navig_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'navig_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/navigation/navig_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::PlanPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::PlanPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::PlanPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e328a33f1ac3d707db24f1f00f6a5f08";
  }

  static const char* value(const ::navig_msgs::PlanPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe328a33f1ac3d707ULL;
  static const uint64_t static_value2 = 0xdb24f1f00f6a5f08ULL;
};

template<class ContainerAllocator>
struct DataType< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navig_msgs/PlanPathRequest";
  }

  static const char* value(const ::navig_msgs::PlanPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose start_pose\n\
geometry_msgs/Pose goal_pose\n\
string start_location_id\n\
string goal_location_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::navig_msgs::PlanPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_pose);
      stream.next(m.goal_pose);
      stream.next(m.start_location_id);
      stream.next(m.goal_location_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navig_msgs::PlanPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navig_msgs::PlanPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.start_pose);
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
    s << indent << "start_location_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.start_location_id);
    s << indent << "goal_location_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal_location_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_PLANPATHREQUEST_H
