// Generated by gencpp from file bbros_bridge/hd_lookat.msg
// DO NOT EDIT!


#ifndef BBROS_BRIDGE_MESSAGE_HD_LOOKAT_H
#define BBROS_BRIDGE_MESSAGE_HD_LOOKAT_H

#include <ros/service_traits.h>


#include <bbros_bridge/hd_lookatRequest.h>
#include <bbros_bridge/hd_lookatResponse.h>


namespace bbros_bridge
{

struct hd_lookat
{

typedef hd_lookatRequest Request;
typedef hd_lookatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hd_lookat
} // namespace bbros_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bbros_bridge::hd_lookat > {
  static const char* value()
  {
    return "0d2267ae1acd4d7549c1a4e21fcad0ae";
  }

  static const char* value(const ::bbros_bridge::hd_lookat&) { return value(); }
};

template<>
struct DataType< ::bbros_bridge::hd_lookat > {
  static const char* value()
  {
    return "bbros_bridge/hd_lookat";
  }

  static const char* value(const ::bbros_bridge::hd_lookat&) { return value(); }
};


// service_traits::MD5Sum< ::bbros_bridge::hd_lookatRequest> should match 
// service_traits::MD5Sum< ::bbros_bridge::hd_lookat > 
template<>
struct MD5Sum< ::bbros_bridge::hd_lookatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bbros_bridge::hd_lookat >::value();
  }
  static const char* value(const ::bbros_bridge::hd_lookatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bbros_bridge::hd_lookatRequest> should match 
// service_traits::DataType< ::bbros_bridge::hd_lookat > 
template<>
struct DataType< ::bbros_bridge::hd_lookatRequest>
{
  static const char* value()
  {
    return DataType< ::bbros_bridge::hd_lookat >::value();
  }
  static const char* value(const ::bbros_bridge::hd_lookatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bbros_bridge::hd_lookatResponse> should match 
// service_traits::MD5Sum< ::bbros_bridge::hd_lookat > 
template<>
struct MD5Sum< ::bbros_bridge::hd_lookatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bbros_bridge::hd_lookat >::value();
  }
  static const char* value(const ::bbros_bridge::hd_lookatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bbros_bridge::hd_lookatResponse> should match 
// service_traits::DataType< ::bbros_bridge::hd_lookat > 
template<>
struct DataType< ::bbros_bridge::hd_lookatResponse>
{
  static const char* value()
  {
    return DataType< ::bbros_bridge::hd_lookat >::value();
  }
  static const char* value(const ::bbros_bridge::hd_lookatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BBROS_BRIDGE_MESSAGE_HD_LOOKAT_H
