// Generated by gencpp from file hri_msgs/RecognitionResult.msg
// DO NOT EDIT!


#ifndef HRI_MSGS_MESSAGE_RECOGNITIONRESULT_H
#define HRI_MSGS_MESSAGE_RECOGNITIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hri_msgs
{
template <class ContainerAllocator>
struct RecognitionResult_
{
  typedef RecognitionResult_<ContainerAllocator> Type;

  RecognitionResult_()
    : sentences()
    , scores()  {
    }
  RecognitionResult_(const ContainerAllocator& _alloc)
    : sentences(_alloc)
    , scores(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _sentences_type;
  _sentences_type sentences;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _scores_type;
  _scores_type scores;




  typedef boost::shared_ptr< ::hri_msgs::RecognitionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_msgs::RecognitionResult_<ContainerAllocator> const> ConstPtr;

}; // struct RecognitionResult_

typedef ::hri_msgs::RecognitionResult_<std::allocator<void> > RecognitionResult;

typedef boost::shared_ptr< ::hri_msgs::RecognitionResult > RecognitionResultPtr;
typedef boost::shared_ptr< ::hri_msgs::RecognitionResult const> RecognitionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_msgs::RecognitionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_msgs::RecognitionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hri_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/hri/hri_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_msgs::RecognitionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_msgs::RecognitionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_msgs::RecognitionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f96b075bcd484621907ceed990cf074d";
  }

  static const char* value(const ::hri_msgs::RecognitionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf96b075bcd484621ULL;
  static const uint64_t static_value2 = 0x907ceed990cf074dULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_msgs/RecognitionResult";
  }

  static const char* value(const ::hri_msgs::RecognitionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] sentences\n\
float64[] scores\n\
\n\
";
  }

  static const char* value(const ::hri_msgs::RecognitionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentences);
      stream.next(m.scores);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognitionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_msgs::RecognitionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_msgs::RecognitionResult_<ContainerAllocator>& v)
  {
    s << indent << "sentences[]" << std::endl;
    for (size_t i = 0; i < v.sentences.size(); ++i)
    {
      s << indent << "  sentences[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sentences[i]);
    }
    s << indent << "scores[]" << std::endl;
    for (size_t i = 0; i < v.scores.size(); ++i)
    {
      s << indent << "  scores[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.scores[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_MSGS_MESSAGE_RECOGNITIONRESULT_H
