from ._AddUpdateKnownLoc import *
from ._GetPredefinedArmsPoses import *
from ._GetPredefinedQuestions import *
from ._InitKDB import *
from ._KnownLocations import *
from ._StrQueryKDB import *
from ._ask_store_name import *
from ._find_person import *
from ._parse_sentence_cfr import *
from ._place_object import *
from ._planning_cmd import *
from ._search_remember_face import *
from ._wait_for_command import *
from ._wait_for_confirm import *
from ._wait_for_switch import *
