yolo_model:

  config_file:
    name: hsr_challenge_agosto_19.cfg
  weight_file:
    name: hsr_challenge_agosto_19.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
          - bill
          - blue_lego
          - red_lego
          - yellow_lego
          - blue_mug
          - red_mug
          - purple_mug
          - green_mug
          - chocolate_cookies
          - gansito_envelop
          - rope
          - red_towel
          - pineapple_cookies
