// Generated by gencpp from file audio_msgs/srvAngleResponse.msg
// DO NOT EDIT!


#ifndef AUDIO_MSGS_MESSAGE_SRVANGLERESPONSE_H
#define AUDIO_MSGS_MESSAGE_SRVANGLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace audio_msgs
{
template <class ContainerAllocator>
struct srvAngleResponse_
{
  typedef srvAngleResponse_<ContainerAllocator> Type;

  srvAngleResponse_()
    : Angle(0.0)  {
    }
  srvAngleResponse_(const ContainerAllocator& _alloc)
    : Angle(0.0)  {
  (void)_alloc;
    }



   typedef float _Angle_type;
  _Angle_type Angle;




  typedef boost::shared_ptr< ::audio_msgs::srvAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audio_msgs::srvAngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvAngleResponse_

typedef ::audio_msgs::srvAngleResponse_<std::allocator<void> > srvAngleResponse;

typedef boost::shared_ptr< ::audio_msgs::srvAngleResponse > srvAngleResponsePtr;
typedef boost::shared_ptr< ::audio_msgs::srvAngleResponse const> srvAngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::audio_msgs::srvAngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace audio_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_msgs::srvAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_msgs::srvAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_msgs::srvAngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c12d5a3eed4d7589fde4b3bcd93aff0";
  }

  static const char* value(const ::audio_msgs::srvAngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c12d5a3eed4d758ULL;
  static const uint64_t static_value2 = 0x9fde4b3bcd93aff0ULL;
};

template<class ContainerAllocator>
struct DataType< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "audio_msgs/srvAngleResponse";
  }

  static const char* value(const ::audio_msgs::srvAngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Angle\n\
";
  }

  static const char* value(const ::audio_msgs::srvAngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvAngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::audio_msgs::srvAngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::audio_msgs::srvAngleResponse_<ContainerAllocator>& v)
  {
    s << indent << "Angle: ";
    Printer<float>::stream(s, indent + "  ", v.Angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUDIO_MSGS_MESSAGE_SRVANGLERESPONSE_H
