// Generated by gencpp from file vision_msgs/DetectObjectsRequest.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_DETECTOBJECTSREQUEST_H
#define VISION_MSGS_MESSAGE_DETECTOBJECTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct DetectObjectsRequest_
{
  typedef DetectObjectsRequest_<ContainerAllocator> Type;

  DetectObjectsRequest_()
    : saveFiles(false)
    , iterations(0)  {
    }
  DetectObjectsRequest_(const ContainerAllocator& _alloc)
    : saveFiles(false)
    , iterations(0)  {
  (void)_alloc;
    }



   typedef uint8_t _saveFiles_type;
  _saveFiles_type saveFiles;

   typedef int32_t _iterations_type;
  _iterations_type iterations;




  typedef boost::shared_ptr< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectsRequest_

typedef ::vision_msgs::DetectObjectsRequest_<std::allocator<void> > DetectObjectsRequest;

typedef boost::shared_ptr< ::vision_msgs::DetectObjectsRequest > DetectObjectsRequestPtr;
typedef boost::shared_ptr< ::vision_msgs::DetectObjectsRequest const> DetectObjectsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "997612da8ca8df9b7b519109c3ea9614";
  }

  static const char* value(const ::vision_msgs::DetectObjectsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x997612da8ca8df9bULL;
  static const uint64_t static_value2 = 0x7b519109c3ea9614ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/DetectObjectsRequest";
  }

  static const char* value(const ::vision_msgs::DetectObjectsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool saveFiles\n\
int32 iterations\n\
";
  }

  static const char* value(const ::vision_msgs::DetectObjectsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.saveFiles);
      stream.next(m.iterations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectObjectsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::DetectObjectsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::DetectObjectsRequest_<ContainerAllocator>& v)
  {
    s << indent << "saveFiles: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.saveFiles);
    s << indent << "iterations: ";
    Printer<int32_t>::stream(s, indent + "  ", v.iterations);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_DETECTOBJECTSREQUEST_H
