// Generated by gencpp from file vision_msgs/GetCubesRequest.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_GETCUBESREQUEST_H
#define VISION_MSGS_MESSAGE_GETCUBESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision_msgs/CubesSegmented.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct GetCubesRequest_
{
  typedef GetCubesRequest_<ContainerAllocator> Type;

  GetCubesRequest_()
    : cubes_input()  {
    }
  GetCubesRequest_(const ContainerAllocator& _alloc)
    : cubes_input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vision_msgs::CubesSegmented_<ContainerAllocator>  _cubes_input_type;
  _cubes_input_type cubes_input;




  typedef boost::shared_ptr< ::vision_msgs::GetCubesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::GetCubesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCubesRequest_

typedef ::vision_msgs::GetCubesRequest_<std::allocator<void> > GetCubesRequest;

typedef boost::shared_ptr< ::vision_msgs::GetCubesRequest > GetCubesRequestPtr;
typedef boost::shared_ptr< ::vision_msgs::GetCubesRequest const> GetCubesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::GetCubesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::GetCubesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::GetCubesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::GetCubesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d157fc83cf257e6044b1e57d3508700";
  }

  static const char* value(const ::vision_msgs::GetCubesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d157fc83cf257e6ULL;
  static const uint64_t static_value2 = 0x044b1e57d3508700ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/GetCubesRequest";
  }

  static const char* value(const ::vision_msgs::GetCubesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/CubesSegmented cubes_input\n\
\n\
================================================================================\n\
MSG: vision_msgs/CubesSegmented\n\
std_msgs/Header header\n\
vision_msgs/Cube[] recog_cubes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: vision_msgs/Cube\n\
string color #color of the cube\n\
geometry_msgs/Point cube_centroid		#Cube Centroid (x,y,z)\n\
bool detected_cube    #flag to indicate if the cube was detected\n\
geometry_msgs/Point minPoint	#Cube's min point\n\
geometry_msgs/Point maxPoint	#Cube's max point\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vision_msgs::GetCubesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cubes_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCubesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::GetCubesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::GetCubesRequest_<ContainerAllocator>& v)
  {
    s << indent << "cubes_input: ";
    s << std::endl;
    Printer< ::vision_msgs::CubesSegmented_<ContainerAllocator> >::stream(s, indent + "  ", v.cubes_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_GETCUBESREQUEST_H
