// Generated by gencpp from file vision_msgs/SkeletonJoint.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_SKELETONJOINT_H
#define VISION_MSGS_MESSAGE_SKELETONJOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct SkeletonJoint_
{
  typedef SkeletonJoint_<ContainerAllocator> Type;

  SkeletonJoint_()
    : name_joint()
    , position()
    , orientation()  {
    }
  SkeletonJoint_(const ContainerAllocator& _alloc)
    : name_joint(_alloc)
    , position(_alloc)
    , orientation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _name_joint_type;
  _name_joint_type name_joint;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;




  typedef boost::shared_ptr< ::vision_msgs::SkeletonJoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::SkeletonJoint_<ContainerAllocator> const> ConstPtr;

}; // struct SkeletonJoint_

typedef ::vision_msgs::SkeletonJoint_<std::allocator<void> > SkeletonJoint;

typedef boost::shared_ptr< ::vision_msgs::SkeletonJoint > SkeletonJointPtr;
typedef boost::shared_ptr< ::vision_msgs::SkeletonJoint const> SkeletonJointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::SkeletonJoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::SkeletonJoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::SkeletonJoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::SkeletonJoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc5468d1135a7ad558e21de9fa6840a5";
  }

  static const char* value(const ::vision_msgs::SkeletonJoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc5468d1135a7ad5ULL;
  static const uint64_t static_value2 = 0x58e21de9fa6840a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/SkeletonJoint";
  }

  static const char* value(const ::vision_msgs::SkeletonJoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String name_joint\n\
geometry_msgs/Vector3 position\n\
geometry_msgs/Quaternion orientation\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::vision_msgs::SkeletonJoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name_joint);
      stream.next(m.position);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SkeletonJoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::SkeletonJoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::SkeletonJoint_<ContainerAllocator>& v)
  {
    s << indent << "name_joint: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.name_joint);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_SKELETONJOINT_H
