// Generated by gencpp from file vision_msgs/VisionFaceTrainObject.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_VISIONFACETRAINOBJECT_H
#define VISION_MSGS_MESSAGE_VISIONFACETRAINOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct VisionFaceTrainObject_
{
  typedef VisionFaceTrainObject_<ContainerAllocator> Type;

  VisionFaceTrainObject_()
    : id()
    , frames(0)  {
    }
  VisionFaceTrainObject_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , frames(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef int32_t _frames_type;
  _frames_type frames;




  typedef boost::shared_ptr< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> const> ConstPtr;

}; // struct VisionFaceTrainObject_

typedef ::vision_msgs::VisionFaceTrainObject_<std::allocator<void> > VisionFaceTrainObject;

typedef boost::shared_ptr< ::vision_msgs::VisionFaceTrainObject > VisionFaceTrainObjectPtr;
typedef boost::shared_ptr< ::vision_msgs::VisionFaceTrainObject const> VisionFaceTrainObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'vision_msgs': ['/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg', '/home/hsr_pumas/HSR_PUMAS/catkin_ws/src/vision/vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3e8e25fcbb0fb9e09f30fa7d99356d3";
  }

  static const char* value(const ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3e8e25fcbb0fb9eULL;
  static const uint64_t static_value2 = 0x09f30fa7d99356d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/VisionFaceTrainObject";
  }

  static const char* value(const ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id                                    #face id\n\
int32 frames                                 #Number of frames to train\n\
";
  }

  static const char* value(const ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.frames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionFaceTrainObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::VisionFaceTrainObject_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "frames: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frames);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_VISIONFACETRAINOBJECT_H
